### ISSUE TITLE
Add CSS

### ISSUE THREAD

**Issue by nmke-de** [nmke-de/HANSI#1]
[hansi.css](https://github.com/nmke-de/HANSI/hansi.css) is currently empty.

**Comment by nmke-de** [comment]
#2 is good (thx @SalmanShahid888), but there are some CSS rules that I probably won't need, and some other I require. I will make edits later.

**Comment by SalmanShahid888** [comment]
@nmke-de 

- Can you please edit the ReadMe file on your project to get a better understanding of what the project is about.

**Comment by nmke-de** [comment]
Sure, but it is currently not my priority.

**Comment by nmke-de** [comment]
I have added a readme.
