### ISSUE TITLE
Bug mit den kleinen Tags der Werte 

### ISSUE THREAD

**Issue by The-Account** [nmke-de/HANSI#6]
Bei den Attribut-Tags der Werte wird nur ein einziger angezeigt, auch wenn es mehrere Attribute geben sollte. Das wird man irgendwie mit JS lösen müssen.

**Comment by nmke-de** [comment]
Fixed it with [e7511d4](https://github.com/nmke-de/HANSI/tree/e7511d4df4a0d79168818198f45c00174dae8c24).
